services:
  node0:
    image: miketango2002/traffic_generator
    command: ['0']
    networks:
    - edge_0_1
    - edge_0_5
  node1:
    image: miketango2002/traffic_generator
    command: ['1']
    networks:
    - edge_1_6
    - edge_1_3
    - edge_1_2
    - edge_0_1
  node2:
    image: miketango2002/traffic_generator
    command: ['2']
    networks:
    - edge_1_2
  node3:
    image: miketango2002/traffic_generator
    command: ['3']
    networks:
    - edge_3_4
    - edge_1_3
  node4:
    image: miketango2002/traffic_generator
    command: ['4']
    networks:
    - edge_3_4
  node5:
    image: miketango2002/traffic_generator
    command: ['5']
    networks:
    - edge_5_7
    - edge_5_9
    - edge_0_5
  node6:
    image: miketango2002/traffic_generator
    command: ['6']
    networks:
    - edge_6_8
    - edge_1_6
  node7:
    image: miketango2002/traffic_generator
    command: ['7']
    networks:
    - edge_5_7
  node8:
    image: miketango2002/traffic_generator
    command: ['8']
    networks:
    - edge_6_8
  node9:
    image: miketango2002/traffic_generator
    command: ['9']
    networks:
    - edge_5_9
networks:
  edge_5_7:
  edge_6_8:
  edge_5_9:
  edge_1_6:
  edge_3_4:
  edge_1_3:
  edge_1_2:
  edge_0_1:
  edge_0_5:
